"""updated gatepass workflow

Revision ID: 2762ae73c568
Revises: 2e6e5dc522e7
Create Date: 2025-11-05 15:21:30.471852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2762ae73c568'
down_revision = '2e6e5dc522e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('to_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_contact', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('entry_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('return_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gate_pass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('entry_time')
        batch_op.drop_column('parent_contact')
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')

    # ### end Alembic commands ###
